# Generated by Django 4.1 on 2022-08-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registered",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(verbose_name="Timestamp")),
                ("s_name", models.CharField(max_length=120, verbose_name="Surname")),
                (
                    "f_name_m",
                    models.CharField(max_length=120, verbose_name="Firstname Male"),
                ),
                (
                    "phone_no_m",
                    models.CharField(max_length=11, verbose_name="Phone Number Male"),
                ),
                (
                    "email_m",
                    models.EmailField(max_length=254, verbose_name="Email Male"),
                ),
                (
                    "f_name_f",
                    models.CharField(max_length=120, verbose_name="Firstname Female"),
                ),
                (
                    "phone_no_f",
                    models.CharField(max_length=11, verbose_name="Phone Number Female"),
                ),
                (
                    "email_f",
                    models.EmailField(max_length=254, verbose_name="Email Female"),
                ),
                (
                    "no_of_years_married",
                    models.IntegerField(verbose_name="Number of Years married"),
                ),
                (
                    "attended_previous",
                    models.CharField(
                        max_length=120, verbose_name="Attended Previous version?"
                    ),
                ),
                (
                    "how_heard_about_program",
                    models.CharField(
                        max_length=120, verbose_name="How you heard about program"
                    ),
                ),
                (
                    "means_of_communication",
                    models.CharField(
                        max_length=120, verbose_name="Preferred means of communication"
                    ),
                ),
                ("comments", models.TextField(blank=True)),
            ],
        ),
    ]
