# Generated by Django 4.1 on 2022-08-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_alter_registered_no_of_years_married"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registered",
            name="attended_previous",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Attended Previous version?"
            ),
        ),
        migrations.AlterField(
            model_name="registered",
            name="email_f",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Email Female"
            ),
        ),
        migrations.AlterField(
            model_name="registered",
            name="email_m",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Email Male"
            ),
        ),
        migrations.AlterField(
            model_name="registered",
            name="f_name_f",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Firstname Female"
            ),
        ),
        migrations.AlterField(
            model_name="registered",
            name="f_name_m",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Firstname Male"
            ),
        ),
        migrations.AlterField(
            model_name="registered",
            name="how_heard_about_program",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="How you heard about program"
            ),
        ),
        migrations.AlterField(
            model_name="registered",
            name="means_of_communication",
            field=models.CharField(
                blank=True,
                max_length=120,
                verbose_name="Preferred means of communication",
            ),
        ),
        migrations.AlterField(
            model_name="registered",
            name="no_of_years_married",
            field=models.CharField(
                blank=True, max_length=5, verbose_name="Number of Years married"
            ),
        ),
        migrations.AlterField(
            model_name="registered",
            name="phone_no_f",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="Phone Number Female"
            ),
        ),
        migrations.AlterField(
            model_name="registered",
            name="phone_no_m",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="Phone Number Male"
            ),
        ),
        migrations.AlterField(
            model_name="registered",
            name="s_name",
            field=models.CharField(blank=True, max_length=120, verbose_name="Surname"),
        ),
        migrations.AlterField(
            model_name="registered",
            name="timestamp",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Timestamp"
            ),
        ),
    ]
