# Generated by Django 4.1 on 2022-08-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_alter_registered_attended_previous_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registered",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
