# Generated by Django 4.1 on 2022-09-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_alter_registered_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="registered",
            name="present",
            field=models.CharField(max_length=100, null=True, verbose_name="Present?"),
        ),
        migrations.AlterField(
            model_name="registered",
            name="how_heard_about_program",
            field=models.CharField(
                blank=True,
                max_length=120,
                null=True,
                verbose_name="How you heard about program",
            ),
        ),
    ]
