# Generated by Django 4.1 on 2022-09-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_registered_present_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registered",
            name="present",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Attendance"
            ),
        ),
    ]
