# Generated by Django 5.1.3 on 2025-02-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_registered_present'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registered',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='registered',
            name='means_of_communication',
        ),
        migrations.RemoveField(
            model_name='registered',
            name='no_of_years_married',
        ),
        migrations.RemoveField(
            model_name='registered',
            name='present',
        ),
        migrations.AddField(
            model_name='registered',
            name='year_married',
            field=models.IntegerField(default=1998, verbose_name='Year Married'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registered',
            name='attended_previous',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, verbose_name='Attended Previous version?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registered',
            name='email_f',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Female'),
        ),
        migrations.AlterField(
            model_name='registered',
            name='email_m',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Male'),
        ),
        migrations.AlterField(
            model_name='registered',
            name='f_name_f',
            field=models.CharField(default='Funmi', max_length=120, verbose_name='Firstname Female'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registered',
            name='f_name_m',
            field=models.CharField(default='Ade', max_length=120, verbose_name='Firstname Male'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registered',
            name='how_heard_about_program',
            field=models.CharField(default='Flyer', max_length=255, verbose_name='How you heard about program'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registered',
            name='phone_no_f',
            field=models.CharField(default='2348023164767', max_length=40, unique=True, verbose_name='Phone Number Female'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registered',
            name='phone_no_m',
            field=models.CharField(default='2348023164767', max_length=40, unique=True, verbose_name='Phone Number Male'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registered',
            name='s_name',
            field=models.CharField(default='Aluko', max_length=120, verbose_name='Surname'),
            preserve_default=False,
        ),
    ]
