# Generated by Django 5.1.3 on 2025-02-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_registered_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered',
            name='phone_no_f',
            field=models.CharField(max_length=40, verbose_name='Phone Number Female'),
        ),
        migrations.AlterField(
            model_name='registered',
            name='phone_no_m',
            field=models.CharField(max_length=40, verbose_name='Phone Number Male'),
        ),
    ]
