# Generated by Django 5.1.3 on 2025-02-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_registered_phone_no_f_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered',
            name='phone_no_f',
            field=models.CharField(max_length=40, unique=True, verbose_name='Phone Number Female'),
        ),
        migrations.AlterField(
            model_name='registered',
            name='phone_no_m',
            field=models.CharField(max_length=40, unique=True, verbose_name='Phone Number Male'),
        ),
    ]
