# Generated by Django 5.1.3 on 2025-02-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_registered_phone_no_f_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='registered',
            name='attended_previous',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Attended Previous Version?'),
        ),
        migrations.AlterField(
            model_name='registered',
            name='email_f',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="Wife's Email"),
        ),
        migrations.AlterField(
            model_name='registered',
            name='email_m',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="Husband's Email"),
        ),
        migrations.AlterField(
            model_name='registered',
            name='f_name_f',
            field=models.CharField(max_length=120, verbose_name="Wife's First Name"),
        ),
        migrations.AlterField(
            model_name='registered',
            name='f_name_m',
            field=models.CharField(max_length=120, verbose_name="Husband's First Name"),
        ),
        migrations.AlterField(
            model_name='registered',
            name='how_heard_about_program',
            field=models.CharField(max_length=255, verbose_name='How You Heard About Program'),
        ),
        migrations.AlterField(
            model_name='registered',
            name='phone_no_f',
            field=models.CharField(max_length=40, unique=True, verbose_name="Wife's Phone Number"),
        ),
        migrations.AlterField(
            model_name='registered',
            name='phone_no_m',
            field=models.CharField(max_length=40, unique=True, verbose_name="Husband's Phone Number"),
        ),
    ]
