# Generated by Django 5.1.3 on 2025-04-09 03:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_registered_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered',
            name='unique_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
