# Generated by Django 5.1.3 on 2025-04-09 03:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_registered_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registered',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='registered',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registered',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
