# Generated by Django 5.1.3 on 2025-04-09 04:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_remove_registered_timestamp_registered_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
