# Generated by Django 5.1.3 on 2025-04-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_registered_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered',
            name='has_confirmed_attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registered',
            name='has_downloaded_tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registered',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
    ]
