# Generated by Django 5.1.3 on 2025-04-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_registered_has_confirmed_attendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
    ]
