# Generated by Django 5.1.3 on 2025-05-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_registered_labourer'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered',
            name='labourer_note',
            field=models.TextField(blank=True, verbose_name='Labourer Note'),
        ),
    ]
