# Generated by Django 5.1.3 on 2025-05-24 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_seminar_registered_seminar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seminar',
            new_name='Breakouts',
        ),
        migrations.RenameField(
            model_name='registered',
            old_name='seminar',
            new_name='breakout',
        ),
    ]
