# Generated by Django 5.1.3 on 2025-06-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_rename_seminar_breakouts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
