# Generated by Django 5.1.3 on 2025-06-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered',
            name='is_present_day2',
            field=models.BooleanField(default=False),
        ),
    ]
