# Generated by Django 5.1.3 on 2025-06-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_registered_is_present_day2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField()),
                ('surname', models.CharField(max_length=120)),
                ('registration_code', models.CharField(max_length=6)),
                ('satisfaction', models.CharField(choices=[('Very dissatisfied', 'Very dissatisfied'), ('Dissatisfied', 'Dissatisfied'), ('Neutral', 'Neutral'), ('Satisfied', 'Satisfied'), ('Very satisfied', 'Very satisfied')], max_length=20)),
                ('usability', models.CharField(choices=[('Very difficult', 'Very difficult'), ('Difficult', 'Difficult'), ('Neutral', 'Neutral'), ('Easy', 'Easy'), ('Very easy', 'Very easy')], max_length=20)),
                ('completion', models.CharField(choices=[('No, I couldn’t do most things', 'No, I couldn’t do most things'), ('I had a few issues', 'I had a few issues'), ('Neutral', 'Neutral'), ('Yes, mostly smooth', 'Yes, mostly smooth'), ('Everything worked perfectly', 'Everything worked perfectly')], max_length=40)),
                ('suggestions', models.TextField(blank=True)),
                ('seminar_ideas', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
