# Generated by Django 5.1.3 on 2024-12-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(blank=True, max_length=100, null=True)),
                ('f_name_m', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_no_m', models.CharField(blank=True, max_length=20, null=True)),
                ('email_m', models.EmailField(blank=True, max_length=254, null=True)),
                ('f_name_f', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_no_f', models.CharField(blank=True, max_length=20, null=True)),
                ('email_f', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_user', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.IntegerField()),
                ('delivery_method', models.JSONField()),
                ('delivery_time', models.CharField(max_length=20)),
                ('schedule_date', models.DateField(blank=True, null=True)),
                ('schedule_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipients', models.ManyToManyField(related_name='messages', to='messaging_engine.recipient')),
            ],
        ),
    ]
