# Generated by Django 5.1.3 on 2025-02-06 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_engine', '0002_recipient_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='template_id',
        ),
        migrations.AddField(
            model_name='message',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='messaging_engine.messagetemplate'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('message_content', models.TextField()),
                ('channel', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging_engine.message')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging_engine.recipient')),
            ],
        ),
    ]
