# Generated by Django 5.1.3 on 2025-02-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_engine', '0003_remove_message_template_id_message_template_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagelog',
            old_name='error_message',
            new_name='response_data',
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
