# Generated by Django 5.1.3 on 2025-04-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_engine', '0004_rename_error_message_messagelog_response_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='registered_ref',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
